<a href="https://colab.research.google.com/github/MarcosAaronF0X/MarcosAaronF0X/blob/main/Imers%C3%A3o_Python_Alura_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv')
df.head(10)

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M
5,2025.0,EN,FT,Data Engineer,80000,USD,80000,US,0,US,M
6,2025.0,SE,FT,Data Scientist,185000,USD,185000,US,0,US,M
7,2025.0,SE,FT,Data Scientist,148000,USD,148000,US,0,US,M
8,2025.0,MI,FT,Data Scientist,135000,USD,135000,CA,0,CA,M
9,2025.0,MI,FT,Data Scientist,108000,USD,108000,CA,0,CA,M

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [8]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [9]:
df.shape

(133349, 11)

In [11]:
linhas, colunas = df.shape[0], df.shape[1]
print('linhas: ', linhas)
print('colunas: ', colunas)

linhas:  133349
colunas:  11

In [22]:
df.columns

Index(['ano', 'nivel_experiencia', 'tipo_emprego', 'cargo', 'salario', 'moeda',
       'usd', 'residencia', 'percentual_remoto', 'localizacao_empresa',
       'porte_empresa'],
      dtype='object')

In [23]:
df.columns

# Mapeamento dos nomes das colunas para o português do Brasil
colunas_traduzidas = {
    'ano': 'ano',
    'nivel_experiencia': 'nivel_experiencia',
    'tipo_emprego': 'tipo_emprego',
    'cargo': 'cargo',
    'salario': 'salario',
    'moeda_salario': 'moeda',
    'salario_em_usd': 'usd',
    'residencia_funcionario': 'residencia',
    'percentual_remoto': 'percentual_remoto',
    'localizacao_empresa': 'localizacao_empresa',
    'porte_empresa': 'porte_empresa'
}

# Renomear as colunas do DataFrame
df = df.rename(columns=colunas_traduzidas)

# Exibir as novas colunas para verificar a tradução
print('Novas colunas do DataFrame:')
print(df.columns)

Novas colunas do DataFrame:
Index(['ano', 'nivel_experiencia', 'tipo_emprego', 'cargo', 'salario', 'moeda',
       'usd', 'residencia', 'percentual_remoto', 'localizacao_empresa',
       'porte_empresa'],
      dtype='object')

In [24]:
df['nivel_experiencia'].value_counts()

nivel_experiencia
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [25]:
df['tipo_emprego'].value_counts()

tipo_emprego
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [26]:
df['percentual_remoto'].value_counts()

percentual_remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [27]:
df['porte_empresa'].value_counts()

porte_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [28]:
mapeamento_nivel_experiencia = {
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'Junior',
    'EX': 'Executivo'
}
df['nivel_experiencia'] = df['nivel_experiencia'].map(mapeamento_nivel_experiencia)
print(df['nivel_experiencia'].value_counts())

nivel_experiencia
Senior       77241
Pleno        40465
Junior       12443
Executivo     3200
Name: count, dtype: int64

In [29]:
mapeamento_tipo_emprego = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Meio Período',
    'FL': 'Freelancer'
}
df['tipo_emprego'] = df['tipo_emprego'].map(mapeamento_tipo_emprego)
print(df['tipo_emprego'].value_counts())

tipo_emprego
Tempo Integral    132563
Contrato             394
Meio Período         376
Freelancer            16
Name: count, dtype: int64

In [30]:
mapeamento_porte_empresa = {
    'M': 'Médio',
    'L': 'Grande',
    'S': 'Pequeno'
}
df['porte_empresa'] = df['porte_empresa'].map(mapeamento_porte_empresa)
print(df['porte_empresa'].value_counts())

porte_empresa
Médio      129561
Grande       3574
Pequeno       214
Name: count, dtype: int64

In [31]:
mapeamento_percentual_remoto = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Totalmente Remoto'
}
df['percentual_remoto'] = df['percentual_remoto'].map(mapeamento_percentual_remoto)
print(df['percentual_remoto'].value_counts())

percentual_remoto
Presencial           105312
Totalmente Remoto     27718
Híbrido                 319
Name: count, dtype: int64

In [33]:
df.head(20)

,ano,nivel_experiencia,tipo_emprego,cargo,salario,moeda,usd,residencia,percentual_remoto,localizacao_empresa,porte_empresa
0,2025.0,Senior,Tempo Integral,Solutions Engineer,214000,USD,214000,US,Totalmente Remoto,US,Médio
1,2025.0,Senior,Tempo Integral,Solutions Engineer,136000,USD,136000,US,Totalmente Remoto,US,Médio
2,2025.0,Pleno,Tempo Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Médio
3,2025.0,Pleno,Tempo Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Médio
4,2025.0,Junior,Tempo Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Médio
5,2025.0,Junior,Tempo Integral,Data Engineer,80000,USD,80000,US,Presencial,US,Médio
6,2025.0,Senior,Tempo Integral,Data Scientist,185000,USD,185000,US,Presencial,US,Médio
7,2025.0,Senior,Tempo Integral,Data Scientist,148000,USD,148000,US,Presencial,US,Médio
8,2025.0,Pleno,Tempo Integral,Data Scientist,135000,USD,135000,CA,Presencial,CA,Médio
9,2025.0,Pleno,Tempo Integral,Data Scientist,108000,USD,108000,CA,Presencial,CA,Médio
10,2025.0,Pleno,Tempo Integral,BI Developer,118000,USD,118000,US,Totalmente Remoto,US,Médio
11,2025.0,Pleno,Tempo Integral,BI Developer,51000,USD,51000,US,Totalmente Remoto,US,Médio
12,2025.0,Junior,Tempo Integral,Data Analyst,91900,USD,91900,US,Presencial,US,Médio
13,2025.0,Junior,Tempo Integral,Data Analyst,54300,USD,54300,US,Presencial,US,Médio
14,2025.0,Senior,Tempo Integral,Applied Scientist,255000,USD,255000,US,Presencial,US,Médio
15,2025.0,Senior,Tempo Integral,Applied Scientist,190000,USD,190000,US,Presencial,US,Médio
16,2025.0,Pleno,Tempo Integral,Systems Engineer,196350,USD,196350,US,Presencial,US,Médio
17,2025.0,Pleno,Tempo Integral,Systems Engineer,130900,USD,130900,US,Presencial,US,Médio
18,2025.0,Executivo,Tempo Integral,Director,170000,USD,170000,US,Presencial,US,Médio
19,2025.0,Executivo,Tempo Integral,Director,160000,USD,160000,US,Presencial,US,Médio

In [34]:
df.describe(include='object')

,nivel_experiencia,tipo_emprego,cargo,moeda,residencia,percentual_remoto,localizacao_empresa,porte_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Tempo Integral,Data Scientist,USD,US,Presencial,US,Médio
freq,77241,132563,17314,126140,119579,105312,119641,129561